### ISSUE TITLE
大神你好，遇到问题想请教一下

### ISSUE THREAD

**Issue by nealtsai888** [crazypeace/v2ray_wss#11]
大神你好，我是看的这个帖子进行操作的，全程安装攻略进行，对照日志排查出有可能是这个原因，帮忙看看为什么安装不了？
https://zelikk.blogspot.com/2022/04/woiden-ipv6-vps-v2ray-vless-websocket-tls.html 

错误日志：
指定安装V2ray v4.45.2版本
----------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22189  100 22189    0     0   160k      0 --:--:-- --:--:-- --:--:--  160k
info: Installing V2Ray v4.45.2 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.45.2/v2ray-linux-64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Terminated
error: Download failed! Please check your network or try again.
removed: /tmp/tmp.XubRS5r9MW
Failed to enable unit: Unit file v2ray.service does not exist.

脚本使用的是这个
bash <(curl -L https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2/raw/main/install.sh)

**Comment by crazypeace** [comment]
你好! 你反馈时提供的日志很好!
看起来确实是这一步出了问题。
你在你的vps的命令行直接下载这个包看能否下载？
```wget https://github.com/v2fly/v2ray-core/releases/download/v4.45.2/v2ray-linux-64.zip```

你在woiden上面搭梯子，warp弄好了没有？

**Comment by nealtsai888** [comment]
你好，感谢回答，warp我用的是攻略里的这个命令，bash <(curl -L https://raw.githubusercontents.com/crazypeace/warp.sh/main/warp.sh) 4 && bash <(curl -L https://raw.githubusercontents.com/crazypeace/warp.sh/main/wgcf_postup_postdown.sh) 日志如下：
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40555  100 40555    0     0   6459      0  0:00:06  0:00:06 --:--:--  8697

__        ___    ____  ____    ___           _        _ _           
\ \      / / \  |  _ \|  _ \  |_ _|_ __  ___| |_ __ _| | | ___ _ __ 
 \ \ /\ / / _ \ | |_) | |_) |  | || '_ \/ __| __/ _` | | |/ _ \ '__|
  \ V  V / ___ \|  _ <|  __/   | || | | \__ \ || (_| | | |  __/ |   
   \_/\_/_/   \_\_| \_\_|     |___|_| |_|___/\__\__,_|_|_|\___|_|   
                                                                    
Copyright (C) P3TERX.COM | https://github.com/P3TERX/warp.sh

Modified: https://github.com/crazypeace/warp.sh
Welcome any feedback on Github or Telegram: https://t.me/+ISuvkzFGZPBhMzE1

System Information
---------------------------------------------------
  Operating System: Debian GNU/Linux 11 (bullseye)
      Linux Kernel: 3.10.0-1160.53.1.vz7.185.3
      Architecture: x86_64
    Virtualization: openvz
---------------------------------------------------

[INFO] WireGuard is installed and running.
[INFO] Disabling WireGuard...
Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service.
[INFO] WireGuard has been disabled.
[INFO] Getting the network interface IPv6 address...
[INFO] IPv6 Address: 2a03:cfc0:8004::b:1b58
[INFO] Getting the best MTU value for WireGuard...
[INFO] WireGuard MTU: 1400
[INFO] WireGuard profile (/etc/wireguard/wgcf.conf) generation in progress...
========================================================================================================================================
# Generated by P3TERX/warp.sh
# Visit https://github.com/P3TERX/warp.sh for more information

[Interface]
PrivateKey = EIIytP6lY767ttv5+H8RQEo88WtqieF5oHOsxVcGdHE=
Address = 172.16.0.2/32,2606:4700:110:8c77:ec2a:65a9:4490:9720/128
DNS = 2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4
MTU = 1400

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
AllowedIPs = 0.0.0.0/0
Endpoint = [2606:4700:d0::a29f:c001]:2408
========================================================================================================================================
[INFO] Starting WireGuard...
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wgcf.service → /lib/systemd/system/wg-quick@.service.
[INFO] WireGuard is running.
[INFO] Status check in progress...

 ----------------------------
 WireGuard	: Running
 IPv4 Network	: Normal
 IPv6 Network	: Normal
 ----------------------------

[INFO] Done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   393  100   393    0     0     82      0  0:00:04  0:00:04 --:--:--    82
[#] ip -4 rule delete table 51820
[#] ip -4 rule delete table main suppress_prefixlength 0
[#] ip link delete dev wgcf
[#] resolvconf -d wgcf -f
[#] iptables-restore -n
[#] ip link add wgcf type wireguard
RTNETLINK answers: Operation not supported
[!] Missing WireGuard kernel module. Falling back to slow userspace implementation.
[#] wireguard-go wgcf
┌──────────────────────────────────────────────────────┐
│                                                      │
│   Running wireguard-go is not required because this  │
│   kernel has first class support for WireGuard. For  │
│   information on installing the kernel module,       │
│   please visit:                                      │
│         https://www.wireguard.com/install/           │
│                                                      │
└──────────────────────────────────────────────────────┘
[#] wg setconf wgcf /dev/fd/62
[#] ip -4 address add 172.16.0.2/32 dev wgcf
[#] ip -6 address add 2606:4700:110:8c77:ec2a:65a9:4490:9720/128 dev wgcf
[#] ip link set mtu 1400 up dev wgcf
[#] resolvconf -a wgcf -m 0 -x
[#] wg set wgcf fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wgcf table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] sysctl -q net.ipv4.conf.all.src_valid_mark=1
[#] iptables-restore -n
[#] ip -4 rule add from 192.168.0.234 lookup main


运行wget https://github.com/v2fly/v2ray-core/releases/download/v4.45.2/v2ray-linux-64.zip 提示如下：
--2023-01-18 20:34:53--  https://github.com/v2fly/v2ray-core/releases/download/v4.45.2/v2ray-linux-64.zip
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
Terminated

**Comment by crazypeace** [comment]
```
WireGuard : Running
IPv4 Network : Normal
IPv6 Network : Normal
```
说明 IPv4 出站没建起来，如果建起来了状态不是 Normal, 应该是 WARP

你试试 warp-go
```
wget -N https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh && bash warp-go.sh 4
```

**Comment by nealtsai888** [comment]
尴尬了，这下直接提示这样
--2023-01-18 23:04:34--  https://raw.githubusercontent.com/fscarmen/warp/main/warp-go.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64985 (63K) [text/plain]
Saving to: 'warp-go.sh'

warp-go.sh                        100%[=============================================================>]  63.46K  --.-KB/s    in 0.02s   

Last-modified header missing -- time-stamps turned off.
2023-01-18 23:04:34 (3.49 MB/s) - 'warp-go.sh' saved [64985/64985]


 Language:
 1.English (default) 
 2.简体中文 

 Choose: 2

 所有依赖已存在，不需要额外安装 

 检查环境中…… 
 没有找到适合的方案用于修改 warp-go 配置文件 warp.conf，脚本中止。当你看到此信息，请把该 bug 反馈至:[https://github.com/fscarmen/warp/issues]

**Comment by crazypeace** [comment]
你可以先重装vps系统，再安装 warp-go 试试。

**Comment by nealtsai888** [comment]
难受，这次是卡在这里失败了。。
 注册 WARP free 账户中, 最大尝试5次…… 
 第1次尝试 
Terminated
 第2次尝试 
Terminated
 第3次尝试 
Terminated
 第4次尝试 
Terminated
 第5次尝试 
Terminated
 注册 WARP free 账户失败，脚本中止，问题反馈: [https://github.com/fscarmen/warp/issues]

**Comment by crazypeace** [comment]
warp现在用的人多了，有时候就是不成功。这也没办法。

**Comment by crazypeace** [comment]
如果想白嫖容器，你可以看看 https://t.me/HiaiFeng/11391 白嫖Doprax
Doprax 官方支持跑v2ray

**Comment by crazypeace** [comment]
如果想买便宜的VPS，可以看看 RN 

RackNerd VPS 年付 $10.28 1G端口 1T流量 10G存储 768M内存
 (https://my.racknerd.com/aff.php?aff=1374&pid=695)https://1ladder.eu.org/rn1028

**Comment by nealtsai888** [comment]
> 如果想白嫖容器，你可以看看 https://t.me/HiaiFeng/11391 白嫖Doprax Doprax 官方支持跑v2ray

谢谢大佬，原来那个不能用了，这个测试目前成功连上了，虽然速度很慢不知道是不是我设置的问题，但是确确实实能用了，太感谢了，大佬厉害666

**Comment by crazypeace** [comment]
不客气，很高兴帮到你！ ：）
