### ISSUE TITLE
指定V2ray v4.45.2，是指服务端？

### ISSUE THREAD

**Issue by predb** [crazypeace/v2ray_wss#12]
还是服务端、客户端都限制在v4.45.2 ？

**Comment by crazypeace** [comment]
![image](https://user-images.githubusercontent.com/665889/214547476-81d4994e-e72b-433b-839d-bceb76302bc6.png)
![image](https://user-images.githubusercontent.com/665889/214547534-c26a3c60-e8d7-4dc2-9e7b-d00cf84e2b8f.png)

```
bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove
rm /etc/apt/sources.list.d/caddy-stable.list
apt remove -y caddy
```

**Comment by crazypeace** [comment]
V5 现在还是 preview 本脚本不会追更新的。[v5.2.1 User Preview](https://github.com/v2fly/v2ray-core/releases/tag/v5.2.1)

**Comment by aimutu** [comment]
> ![image](https://user-images.githubusercontent.com/665889/214547476-81d4994e-e72b-433b-839d-bceb76302bc6.png) ![image](https://user-images.githubusercontent.com/665889/214547534-c26a3c60-e8d7-4dc2-9e7b-d00cf84e2b8f.png)
> 
> ```
> bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove
> rm /etc/apt/sources.list.d/caddy-stable.list
> apt remove -y caddy
> ```

CTRL+F 查了“卸载”，“U**nis**taller” 都没找到。

**Comment by crazypeace** [comment]
https://github.com/crazypeace/v2ray_wss#uninstall

**Comment by crazypeace** [comment]
指定V2ray v4.45.2，是指的服务端。
本脚本搭建的就是服务端。
