### ISSUE TITLE
端口443问题

### ISSUE THREAD

**Issue by tomson6911** [crazypeace/v2ray_wss#14]
安装时已自定义端口 安装后怎么配置显示是443端口？我的vps的443端口被封了。

**Comment by tomson6911** [comment]
谢谢！这个共存的有自定端口的一键脚本吗？

**Comment by crazypeace** [comment]
哈哈，自己修改Caddyfile就行了。
在第1行，域名的后面加上 `:端口`

**Comment by tomson6911** [comment]
谢谢！naive正常使用。但v2ray用不了 主要是443端口被封了（见附图）。附图中的443端口能修改吗？如何修改？![image](https://user-images.githubusercontent.com/20489294/220575832-a235b183-e875-430a-83c2-302b57510365.jpeg)

**Comment by crazypeace** [comment]
443 端口被封 可以套CDN 尝试解决。
如果你想修改443 端口，可以修改Caddyfile，第一行在域名后面加上 `:你的端口`
![image](https://user-images.githubusercontent.com/665889/220866985-b031c987-dd04-45b7-ba67-ca798b0ed2b7.png)

如
```
你的域名:你的端口
{
Caddyfile的其它部分...
```

**Comment by tomson6911** [comment]
谢谢！

**Comment by crazypeace** [comment]
> 

不客气, 很高兴帮到你! :)
