### ISSUE TITLE
大佬，请问下kcp的问题。

### ISSUE THREAD

**Issue by gechao220** [crazypeace/v2ray_wss#15]
脚本安装后，另外加了kcp协议，但是使用warp的时候kcp的就会连接失败，把warp关了，就能连通，是不是要修改什么配置文件？outbound那里需要另外设置吗？

**Comment by crazypeace** [comment]
你装KCP是用于从你这里到VPS，对吧？这是入站。
WARP是指从你的VPS对外访问，对吧？这是出站。
理论上说他们互相之间应该不影响啊。
-
你可以试下装warp的socks5模式，这样不影响系统的路由表。
