### ISSUE TITLE
老板，我创建成功了，如果担心链接泄露，想更换密码生成链接串怎么搞

### ISSUE THREAD

**Issue by tigeratgithub** [crazypeace/v2ray_wss#16]
如题

**Comment by crazypeace** [comment]
如果你啥都不懂，那就脚本再跑一遍。UUID会重新随机生成。

如果你想学习，手动修改。请看 https://zelikk.blogspot.com/2022/05/v2ray-websocket-tls-caddy-path-data-flow.html
