### ISSUE TITLE
求助！cloudflare 代理后 ipv4 环境无法访问

### ISSUE THREAD

**Issue by yanboer** [crazypeace/v2ray_wss#17]
### 1、vps 信息

纯 ipv6 环境，使用 warp 添加了 ipv4 的出站。

### 2、操作步骤

- 使用 ` bash <(curl -L https://github.com/crazypeace/v2ray_wss/raw/main/install.sh) <域名> d` 部署服务。
- cloudflare 开启了代理。
<img width="990" alt="image" src="https://user-images.githubusercontent.com/48461101/235449793-bc186dd7-d885-4047-8142-9c15fed72113.png">

### 3、 结果

- 在移动环境下（支持 ipv6）下，可以正常访问域名并且进入伪装网站。
- 在 wifi 环境下（仅支持 ipv4），无法访问域名，无法进入位置网站。

麻烦请问下，cloudflare 还需要额外的配置吗？
还是我少了哪一步骤。域名是 nl.eu.org 后缀的。

**Comment by crazypeace** [comment]
你的信息比较全，赞一个！
你在wifi环境下，检测一下能不能解析你的域名。

之前有人反馈，中国移动把 eu.org的解析污染了。

**Comment by yanboer** [comment]
域名解析不了，ping 不通。（之前用 hax 的 Cloudflare DNS Pointing 解析域名，本地也是 ping 不通）

刚找我朋友试了下，他是电信带宽没有 ipv6 地址，可以正常访问。
我是移动带宽访问不了。应该就是这个原因了。感谢！

**Comment by crazypeace** [comment]
不客气！ 你的能力还是不错的！
