### ISSUE TITLE
Input 4 for IPv4, 6 for IPv6:

### ISSUE THREAD

**Issue by bk1412** [crazypeace/v2ray_wss#18]
非预设参数手动输入域名后，再Input 4 for IPv4, 6 for IPv6:阶段直接回车会卡住，过段时间会报错提示输入的域名没有解析到本机对应的ip，但是已经成功ip解析了域名

**Comment by bk1412** [comment]
解析错误信息

域名解析错误Domain resolution error....

 你的域名: xxxxx  未解析到:

 你的域名当前解析到: xxxxxx

备注...如果你的域名是使用 Cloudflare 解析的话... 在 DNS 设置页面, 请将代理状 态设置为仅限DNS, 小云朵变灰.
Notice...If you use Cloudflare to resolve your domain, on 'DNS' setting page, 'Proxy status' should be 'DNS only' but not 'Proxied'.

**Comment by crazypeace** [comment]
谢谢反馈!
脚本把检测IP的地方修改了一下.
