### ISSUE TITLE
Options for command line

### ISSUE THREAD

**Issue by LexterS999** [crazypeace/v2ray_wss#19]
How to change redirect site, but not through editing .sh file? Can you add option for command line, please?
And also options for changing ws/grpc.

**Comment by crazypeace** [comment]
Hi, I think the easiest way is fork and edit a version you like.
You can use google and GPT to learn.
Here is a free way to use GPT. https://t.me/gpt_user

**Comment by crazypeace** [comment]
I think another way is that use `sed` command to find `https://zelikk.blogspot.com` and change to another.

I believe GPT can help you a lot.
