### ISSUE TITLE
请问如何自动续期证书呢？

### ISSUE THREAD

**Issue by Suitear** [crazypeace/v2ray_wss#20]
用的下面的历史脚本：

 ``bash <(curl -L https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2/raw/main/install.sh)``

请问如何自动续期证书呢？

**Comment by crazypeace** [comment]
这脚本是自动安装的caddy, 自动续期证书的.

**Comment by SMooxx** [comment]
不行哦，到期了就不会续期，显示526错误我才发现证书又到期了

**Comment by crazypeace** [comment]
1. 你是之前一直可用。从某个时候开始变得不可用了吗？ 
2. 从可用到不可用，你做了什么操作没有？
3. 你在当时使用这个脚本时，是从空白的VPS开始安装的吗？有没有在这之前跑过别的脚本申请证书？
4. 请你发一下你参考的教程的链接。
5. 你查一下目前在使用的caddy的版本
6. 你有没有在脚本的Caddyfile 基础上做什么修改？ 比如，增加自己的网站？

你的环境允许你重新安装吗？你要不要尝试跑一下这个，是用最新的CADDY 和 Xray
`bash <(curl -L https://github.com/crazypeace/v2ray_wss/raw/main/install.sh)`
只要安装过程用到的参数不变（域名，path， UUID等），翻墙客户端的设置就不用改动，可以直接使用。
参考教程：https://zelikk.blogspot.com/2022/11/v2ray-vless-vmess-websocket-cdn-tls-caddy-v2.html

**Comment by crazypeace** [comment]
我想了一下, 还有一种可能就是.
caddy继期证书是需要 http端口(默认是80), https端口(默认是443)都可用的状态.
你自己检查一下吧.
