### ISSUE TITLE
脚本获取到的vps IP跟实际IP不符

### ISSUE THREAD

**Issue by sean908** [crazypeace/v2ray_wss#3]
vps info
```
Username
root
Nat VPS
IPv6
2001:41d0:800:17ac:1234:4321:52ac:0001
```

dns pointing
```
registw.ipv6d.my.id | [2001:41d0:800:17ac:1234:4321:52ac:0001]
```

脚本输出
```
 域名解析错误Domain resolution error....

 你的域名: registw.ipv6d.my.id 未解析到: 2001:41d0:800:17ac::1

 你的域名当前解析到: 2001:41d0:800:17ac:1234:4321:52ac:1
```

**Comment by crazypeace** [comment]
你好，谢谢你的反馈！你附带的信息也足够，非常好！

这个现象是受限于 hax/woiden 的问题。

原理上说，是脚本在VPS上通过curl 访问一下外部的 HTTP url，外部的那台服务器会根据来访的IP地址再返回给这个HTTP请求。
比如：
```
curl -4 -s https://api.myip.la
curl -6 -s https://api.myip.la
curl -s https://api.myip.la
```
如果你看一下其它的一些脚本，类似的HTTP url有：
```
curl https://ip.seeip.org
```

而现在 hax/woiden 的网络环境造成的现象是，用这样的技术去检测VPS本机IP是不准的。

1. 我目前没有发现更好的技术。
2. 我的脚本支持了带参数的方式跳过检测机制，请看 https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2#%E5%B8%A6%E5%8F%82%E6%95%B0%E6%89%A7%E8%A1%8C

在你的环境上你可以使用 `bash <(curl -L https://github.com/crazypeace/V2ray_VLESS_WebSocket_TLS_CaddyV2/raw/main/install.sh) registw.ipv6d.my.id 6`
