### ISSUE TITLE
websocket 握手失败

### ISSUE THREAD

**Issue by qdxkrs** [crazypeace/v2ray_wss#4]
日志如下
2022/09/02 23:32:32 [Warning] [331184489] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxxxxxxxxxxxxx/1234): 200 OK > websocket: bad handshake] > common/retry: all retry attempts failed
2022/09/02 23:32:32 [Warning] [1167798755] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxxxxxxxxxxxxx/1234): 200 OK > websocket: bad handshake] > common/retry: all retry attempts failed
2022/09/02 23:32:32 [Warning] [3448469764] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://xxxxxxxxxxxxxxx/1234): 200 OK > websocket: bad handshake] > common/retry: all retry attempts failed

**Comment by crazypeace** [comment]
推荐你两个排错的教程

第一次装就不成功看这个
https://zelikk.blogspot.com/2022/04/setup-v2ray-websocket-tls-troubleshoot.html

别人能用你不能用看这个
https://zelikk.blogspot.com/2022/04/connect-v2ray-websocket-tls-troubleshoot.html

如果是域名被干扰了，看这两篇无限域名的教程
https://zelikk.blogspot.com/2022/08/v2ray-caddy-v2-tls-ondemand.html
https://zelikk.blogspot.com/2022/08/v2ray-caddy-v2-cloudflare-wildcards-domain-certificate-15year.html
