### ISSUE TITLE
Error WSS

### ISSUE THREAD

**Issue by Rizkyaa** [crazypeace/v2ray_wss#9]
[13:40:31] failed to handler mux client connection > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (*://*/*): 308 Permanent Redirect > websocket: bad handshake] > common/retry: all retry attempts failed

I don't understand the problem where I have tried reinstalling with a different domain and server but still the same error like that

**Comment by crazypeace** [comment]
You need to make sure you can visit https://yourdomain/yourpath 
You can try use your browser to visit it, you should get 400 bad requesst.

If you can't get the "400 bad requesst" from your browser, then your vpn client software can't work too.
https://www.youtube.com/watch?v=13ofpEBUHo0

**Comment by Rizkyaa** [comment]
before I checked the results of mydomain.id/pathwss and the bad request results

**Comment by Rizkyaa** [comment]
[before] I checked the results of mydomain.id/pathwss and the bad request results
![Screenshot_2022-12-04-16-36-31-868-edit_com android chrome](https://user-images.githubusercontent.com/36701336/205483871-a204137a-755d-4bb0-8ed5-5d81f19c97f1.jpg)

**Comment by crazypeace** [comment]
Are you sure the `failed to dial to (:///*): 308 Permanent Redirect` includes the same url in your pic?
![image](https://user-images.githubusercontent.com/36701336/205483871-a204137a-755d-4bb0-8ed5-5d81f19c97f1.jpg)

What `address` you used in your vpn node info? (The No.1 parameter in this pic)
![v2ray-client-configuration](https://user-images.githubusercontent.com/665889/205556757-cb5f66a9-d668-4091-bbe7-95547dc39417.png)
